name: Daily Tech Trends

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4am UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-trends:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run trends script
      run: python src/main.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "tstanmay13@gmail.com"
        git config --local user.name "tstanmay13"
        git add data/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update trends data for $(date +'%Y-%m-%d')"
        git push 