name: Daily Tech Trends Update

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  should-run:
    runs-on: ubuntu-latest
    outputs:
      should_execute: ${{ steps.check.outputs.should_execute }}
    steps:
      - name: Check if we should run
        id: check
        run: |
          # Temporarily set to 100% probability for debugging
          echo "should_execute=true" >> $GITHUB_OUTPUT

  update-trends:
    needs: should-run
    if: needs.should-run.outputs.should_execute == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run trends script
      run: python src/main.py

    - name: Configure Git
      run: |
        git config --global user.email "tstanmay13@gmail.com"
        git config --global user.name "tstanmay13"
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT_TOKEN }}
        commit-message: "Update tech trends"
        title: "Update tech trends"
        body: |
          Automated update of tech trends data.
          This PR was created automatically by the daily trends workflow.
        branch: update-tech-trends
        base: main
        delete-branch: true

  auto-approve:
    needs: update-trends
    if: needs.update-trends.outputs.pull-request-number != ''
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ needs.update-trends.outputs.pull-request-number }},
              event: 'APPROVE'
            })
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ needs.update-trends.outputs.pull-request-number }},
              merge_method: 'squash'
            })